name: Bundle Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: './packages/**/dist/**/*.{ts,js,cjs}' # sourcemap は見ない
