name: Bundle Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Disable PnP
        run: |
          sed -i.bak -e "s/nodeLinker: pnp/nodeLinker: node_modules/g" .yarnrc.yml

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git clean -f
          git commit -am "chore: disable pnp mode"

      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'build'
          clean-script: 'clean'

          # パフォーマンス面の計測よりも、誤って変なものを bundle したことを検知したいので圧縮前で比較する
          compression: 'none'

          # sourcemap は見ない
          # d.ts はたまに異常な数の union 型が展開されるとかは検知したいが見なくて良いかもしれない
          pattern: './packages/**/dist/**/*.{ts,js,cjs}'
