name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs-hosting-main.yml'

env:
  WORKLOAD_IDENTITY_PROVIDER: "projects/643536859873/locations/global/workloadIdentityPools/charcoal/providers/github-actions"
  SERVICE_ACCOUNT_EMAIL: "deployer@pixiv-charcoal-web.iam.gserviceaccount.com"

permissions:
  contents: read
  id-token: write

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest

    environment:
      name: live-channel
      # url: TODO: Edit after

    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: yarn
      # charcoal packages
      - run: yarn install --immutable
      - run: yarn build
      # docs
      - run: yarn add ../packages/react
        working-directory: ./docs
      - run: yarn install
        working-directory: ./docs
      - run: yarn build
        working-directory: ./docs

      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}
      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@v1

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          projectId: pixiv-charcoal-web
          channelId: live