name: gh-pages

on:
  push:
    branches:
      - main
      - deploy-actions # 動作確認

  workflow_dispatch:

jobs:
  storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Prepare deps
        run: |
          yarn install
          yarn build

      - name: Output files
        run: |
          yarn build-storybook -o public --quiet
          cp .storybook/badge.svg public/storybook-badge.svg
          mv docs public/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
