on:
  schedule:
    # only on weekday, at 1:00 UTC ( 10:00 JST )
    - cron: '0 1 * * 1-5'

  workflow_dispatch:

jobs:
  icons:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install deps
        run: |
          yarn install
          yarn workspaces foreach -vptR --from @pixiv-elements/icons-cli run build

      - name: Export
        env:
          FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          OUTPUT_ROOT_DIR: ${{ secrets.OUTPUT_ROOT_DIR }}
        run: yarn icons-cli figma:export

      - name: Optimize
        run: ./icons-cli-optimize.sh

      - name: Create a Pull Request
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: pixiv
          GITHUB_REPO_NAME: charcoal
          GITHUB_DEFAULT_BRANCH: main
        run: yarn icons-cli github:pr
