name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - v4.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: yarn

      - run: yarn install --immutable --inline-builds
      - run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: yarn

      - run: yarn install --immutable --inline-builds
      - run: yarn build
      - run: |
          yarn jest -c packages/react/jest.config.mjs
          yarn jest -c packages/foundation/jest.config.mjs
          yarn jest -c packages/icons/jest.config.mjs
          yarn jest -c packages/react-sandbox/jest.config.mjs
          yarn jest -c packages/styled/jest.config.mjs
          yarn jest -c packages/tailwind-config/jest.config.mjs
          yarn jest -c packages/theme/jest.config.mjs
          yarn jest -c packages/utils/jest.config.mjs
          yarn jest -c .storybook/jest.config.mjs
        env:
          CI: 'true'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: yarn

      - run: yarn install --immutable --inline-builds
      - run: yarn lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: yarn

      - run: yarn install --immutable --inline-builds
      - run: yarn build
      - run: yarn typecheck

  typecheck-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: yarn

      - run: yarn install --immutable --inline-builds
      - run: yarn typecheck:config
