name: test
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: yarn

      - name: Prepare deps
        run: |
          yarn install --immutable --inline-builds
          yarn build

      # TODO: jobを分けてビルド結果をキャッシュして並列化
      - name: Test
        run: |
          yarn test
          yarn lint
          yarn typecheck:config
          yarn typecheck

      - name: Check if Storybook builds
        # storybook の vite build が OOM で落ちることがある
        # これだけ違う job に分離して強い runner で動かすと良いかも？
        run: |
          yarn build-storybook
          NODE_OPTIONS=--max_old_space_size=6144 USE_VITE=1 yarn build-storybook
